const showParagraf = () => {
  let mah = document.getElementById("boh");
  mah.insertAdjacentHTML("afterbegin", merch[giusto()]);
}


const giusto = () => { 
  let i;
  for (i = 0; i < merce.length; i++){
    if (merce[i]===name){
      return i;
    } else if (name==="null"){
      return 13;
    }
  }
}

const carica = () => {
  sessionStorage.setItem("key","molto bello");
  let j = new URL(getLocation(location.href));
  name = j.searchParams.get("find");
  showParagraf();
}   

let merch = ['<div class="container"> <div class="row"> <h3>Muso</h3> </div> <div class="row"> <div class="col"> <img src="https://www.sublimeblog.it/wp-content/uploads/2018/04/giuseppe-zen-mangiari-di-strada-testa-di-maiale-featured.jpg" border="0" alt="Muso di maiale" heigt="400" width="273"> </div> <div class="col"> <p>O\' per e o\' muss è una prelibatezza che si può gustare in quel di Napoli.</p> </div> </div><div class="row"> <div class="col"> <div class="form-group"> <select class="form-control" id="exampleFormControlSelect1"> <option>0</option> <option>1</option> <option>2</option> <option>3</option> <option>4</option> <option>5</option> <option>6</option> <option>7</option> <option>8</option> <option>9</option> <option>10</option> </select> </div> </div> <div class="col"> <button type="button" class="btn btn-success" onclick=addMerch() >Aggiungi al carrello</button> </div> </div> </div>',
    '<div class="container"> <div class="row"> <h3>Orecchio</h3> </div> <div class="row"> <div class="col"> <img src="https://shop-cdn-m.mediazs.com/bilder/orecchie/di/maiale/confezioni/piccole/0/400/50105_pla_dog_snagger_schweineohren_10_stueck_0.jpg" border="0" alt="Orecchio di maiale" heigt="400" width="273"> </div> <div class="col"> <p>Le orecchie sono un taglio del maiale molto poco utilizzato in cucina anche se si prestano a diverse ricette quali insalata di orecchie di maiale, orecchie di maiale croccanti, le orecchie con le verze o le orecchie con fagioli e salsiccia.</p> </div> </div><div class="row"> <div class="col"> <div class="form-group"> <select class="form-control" id="exampleFormControlSelect1"> <option>0</option> <option>1</option> <option>2</option> <option>3</option> <option>4</option> <option>5</option> <option>6</option> <option>7</option> <option>8</option> <option>9</option> <option>10</option> </select> </div> </div> <div class="col"> <button type="button" class="btn btn-success" onclick=addMerch() >Aggiungi al carrello</button> </div> </div> </div>', 
    '<div class="container"> <div class="row"> <h3>Testa</h3> </div> <div class="row"> <div class="col"> <img src="https://www.sublimeblog.it/wp-content/uploads/2018/04/giuseppe-zen-mangiari-di-strada-testa-di-maiale-featured.jpg" border="0" alt="Muso di maiale" heigt="400" width="273"> </div> <div class="col"> <p>“Del maiale, non si butta via niente” recita un noto detto. Proprio niente, appunto, neanche la testa, che può essere oggetto di varie ricette per pietanze molto appetitose come la testa del maiale in cassetta, la testa di maiale lessa o la testa di maiale in gelatina.</p> </div> </div> <div class="row"> <div class="col"> <div class="form-group"> <select class="form-control" id="exampleFormControlSelect1"> <option>0</option> <option>1</option> <option>2</option> <option>3</option> <option>4</option> <option>5</option> <option>6</option> <option>7</option> <option>8</option> <option>9</option> <option>10</option> </select> </div> </div> <div class="col"> <button type="button" class="btn btn-success" onclick=addMerch() >Aggiungi al carrello</button> </div></div></div>',     
    '<div class="container">      <div class="row">          <h3>Guanciale</h3>      </div>      <div class="row">        <div class="col">          <img src="https://www.associazioneproduttoricollinetoscane.it/wp-content/uploads/2018/06/GUANCIALE-DI-MAIALE-1-kg-extra-big-28.jpg" border="0" alt="Guanciale di maiale" heigt="400" width="273">        </div>        <div class="col">          <p>Il guanciale è il taglio di carne suina ricavato dalla guancia del maiale, percorso da venature magre di muscolo con una componente di grasso pregiato, di composizione diversa dal lardo (grasso del dorso) e dalla pancetta (grasso del ventre). La consistenza è più dura rispetto alla pancetta e il sapore più caratteristico. Due degli usi più tipici di questa carne sono l\'amatriciana e la carbonara.</p>        </div>      </div>      <div class="row">        <div class="col">          <div class="form-group">           <select class="form-control" id="exampleFormControlSelect1">     <option>0</option>          <option>1</option>              <option>2</option>              <option>3</option>              <option>4</option>              <option>5</option>              <option>6</option>              <option>7</option>              <option>8</option>              <option>9</option>              <option>10</option>            </select>          </div>        </div>        <div class="col">          <button type="button" class="btn btn-success" onclick=addMerch()>Aggiungi al carrello</button>        </div>      </div>    </div>',
    '<div class="container">      <div class="row">          <h3>Gola</h3>      </div>      <div class="row">        <div class="col">          <img src="https://www.salumificiolarocca.com/foto/articolo/big/gola-salata_2581.jpg" border="0" alt="Gola di maiale" heigt="400" width="273">        </div>        <div class="col">          <p>La gola è un taglio anatomico vicino alla guancia del maiale, vale a dire la parte compresa tra la spalla e la parte inferiore della testa. E’ un salume energetico, un tempo adatto per chi lavorava nei campi e nelle stalle, soprattutto nei mesi invernali.</p>        </div>      </div>      <div class="row">        <div class="col">          <div class="form-group">            <select class="form-control" id="exampleFormControlSelect1">       <option>0</option>       <option>1</option>              <option>2</option>              <option>3</option>              <option>4</option>              <option>5</option>              <option>6</option>              <option>7</option>              <option>8</option>              <option>9</option>              <option>10</option>            </select>          </div>        </div>        <div class="col">          <button type="button" class="btn btn-success" onclick=addMerch()>Aggiungi al carrello</button>        </div>      </div>    </div>', 
    '<div class="container">      <div class="row">          <h3>Carrè</h3>      </div>      <div class="row">        <div class="col">          <img src="https://www.micuncogroup.it/wp-content/uploads/2018/08/suino-carre-t-bologna-0005368-1.jpg" border="0" alt="Carrè di maiale" heigt="400" width="273">        </div>        <div class="col">          <p>Il carrè è molto buono, compralo</p>        </div>      </div>      <div class="row">        <div class="col">          <div class="form-group">            <select class="form-control" id="exampleFormControlSelect1">       <option>0</option>       <option>1</option>              <option>2</option>              <option>3</option>              <option>4</option>              <option>5</option>              <option>6</option>              <option>7</option>              <option>8</option>              <option>9</option>              <option>10</option>            </select>          </div>        </div>        <div class="col">          <button type="button" class="btn btn-success" onclick=addMerch()>Aggiungi al carrello</button>        </div>      </div>    </div>', 
    '<div class="container">      <div class="row">          <h3>Capocollo</h3>      </div>      <div class="row">        <div class="col">          <img src="https://bressanini-lescienze.blogautore.espresso.repubblica.it/files/2016/12/coppa02-800.jpg" border="0" alt="Capocollo di maiale" heigt="400" width="273">        </div>        <div class="col">          <p>Il capocollo è una parte del maiale compresa tra la testa e il lombo (lonza nel caso del suino). Viene chiamata anche scamerita (in Toscana), o coppa (nell\'Italia settentrionale), o locena (in alcune zone dell\'Italia meridionale. Principalmente viene usato per produrre l\'omonimo insaccato. Il taglio comunque è adatto a preparazioni arrosto e, tagliato a fettine, a cotture in padella. </p>        </div>      </div>      <div class="row">        <div class="col">          <div class="form-group">            <select class="form-control" id="exampleFormControlSelect1">      <option>0</option>        <option>1</option>              <option>2</option>              <option>3</option>              <option>4</option>              <option>5</option>              <option>6</option>              <option>7</option>              <option>8</option>              <option>9</option>              <option>10</option>            </select>          </div>        </div>        <div class="col">          <button type="button" class="btn btn-success" onclick=addMerch()>Aggiungi al carrello</button>        </div>      </div>    </div>',
    '<div class="container">      <div class="row">          <h3>Spalla</h3>      </div>      <div class="row">        <div class="col">          <img src="https://www.salepepe.it/files/2014/06/spalla-di-maiale.jpg" border="0" alt="Spalla di maiale" heigt="400" width="273">        </div>        <div class="col">          <p>La spalla di maiale è un taglio che intero, in un suino medio-piccolo, pesa circa 1,5 kg. Benché non molto richiesta, soprattutto nel Nord Italia, la spalla di maiale è molto versatile in cucina, con il vantaggio di essere economica e saporita. È ottima intera arrosto, lasciando attaccata la cotenna in modo che diventi croccante con il calore del grill. Oppure, tagliandola, si può arrostire arrotolata e, a piacere, farcita. E\' molto gustosa anche per preparare il brasato o lo spezzatino.</p>        </div>      </div>      <div class="row">        <div class="col">          <div class="form-group">            <select class="form-control" id="exampleFormControlSelect1">       <option>0</option>       <option>1</option>              <option>2</option>              <option>3</option>              <option>4</option>              <option>5</option>              <option>6</option>              <option>7</option>              <option>8</option>              <option>9</option>              <option>10</option>            </select>          </div>        </div>        <div class="col">          <button type="button" class="btn btn-success" onclick=addMerch()>Aggiungi al carrello</button>        </div>      </div>    </div>',
    '<div class="container">      <div class="row">          <h3>Lombo</h3>      </div>      <div class="row">        <div class="col">          <img src="https://www.granconsigliodellaforchetta.it/wp-content/uploads/2019/01/Lombata-di-maiale-Tagli-di-carne-suina.jpg" border="0" alt="Lombo di maiale" heigt="400" width="273">        </div>        <div class="col">          <p>Il lombo di maiale è sicuramente il taglio di carne suina più conosciuto e, probabilmente, consumato. Si tratta della parte della schiena del maiale escludendone la parte anteriore (il capocollo). I due modi migliori per consumare il lombo di maiale sono l\'arista, cioè l\'arrosto di lombo con osso; e le braciole. </p>        </div>      </div>      <div class="row">        <div class="col">          <div class="form-group">            <select class="form-control" id="exampleFormControlSelect1">       <option>0</option>       <option>1</option>              <option>2</option>              <option>3</option>              <option>4</option>              <option>5</option>              <option>6</option>              <option>7</option>              <option>8</option>              <option>9</option>              <option>10</option>            </select>          </div>        </div>        <div class="col">          <button type="button" class="btn btn-success" onclick=addMerch()>Aggiungi al carrello</button>        </div>      </div>    </div>',
    '<div class="container">      <div class="row">          <h3>Costato</h3>      </div>      <div class="row">        <div class="col">          <img src="https://primochef.it/wp-content/uploads/2019/04/SH_costine-1200x800.jpg" border="0" alt="Costata di maiale" heigt="400" width="273">        </div>        <div class="col">          <p>Le costole del maiale sono un taglio di carne popolare nelle cucine asiatiche e occidentali. La carne e le ossa insieme, viene tagliata in pezzi utilizzabili, preparato da affumicare,grigliare, o da fare al forno - di solito con una salsa, spesso la barbecue - e poi servito. </p>        </div>      </div>      <div class="row">        <div class="col">          <div class="form-group">            <select class="form-control" id="exampleFormControlSelect1">       <option>0</option>       <option>1</option>              <option>2</option>              <option>3</option>              <option>4</option>              <option>5</option>              <option>6</option>              <option>7</option>              <option>8</option>              <option>9</option>              <option>10</option>            </select>          </div>        </div>        <div class="col">          <button type="button" class="btn btn-success" onclick=addMerch()>Aggiungi al carrello</button>        </div>      </div>    </div>',
    '<div class="container">      <div class="row">          <h3>Pancetta</h3>      </div>      <div class="row">        <div class="col">          <img src="https://www.mattonedue.com/wp-content/uploads/2016/03/Pancetta-fresca.jpg" border="0" alt="Pancetta" heigt="400" width="273">        </div>        <div class="col">          <p>La pancetta è un taglio che viene preparato con la parte della pancia dell\'animale. E\' molto versatile in cucina e può essere mangiata singolarmente o inserita in diversi piatti. Inoltre può essere resa croccante al barbecue o in padella ottenendo il cosiddetto bacon.</p>        </div>      </div>      <div class="row">        <div class="col">          <div class="form-group">            <select class="form-control" id="exampleFormControlSelect1">     <option>0</option>         <option>1</option>              <option>2</option>              <option>3</option>              <option>4</option>              <option>5</option>              <option>6</option>              <option>7</option>              <option>8</option>              <option>9</option>              <option>10</option>            </select>          </div>        </div>        <div class="col">          <button type="button" class="btn btn-success" onclick=addMerch()>Aggiungi al carrello</button>        </div>      </div>    </div>',
    '<div class="container">      <div class="row">          <h3>Prosciutto</h3>      </div>      <div class="row">        <div class="col">          <img src="https://www.salumificiopevericarlo.com/blog/wp-content/uploads/2018/02/prosciutto-parma.jpg" border="0" alt="Prosciutto" heigt="400" width="273">        </div>        <div class="col">          <p>Il prosciutto è un taglio che comprende di carne dell\'arto posteriore del maiale, dall\'anca alla prima fila delle ossa tarsali, volgarmente noto come coscia. In campo alimentare viene usato principalmente per la creazione di due salumi: il prosciutto crudo e il prosciutto cotto.</p>        </div>      </div>      <div class="row">        <div class="col">          <div class="form-group">            <select class="form-control" id="exampleFormControlSelect1">       <option>0</option>       <option>1</option>              <option>2</option>              <option>3</option>              <option>4</option>              <option>5</option>              <option>6</option>              <option>7</option>              <option>8</option>              <option>9</option>              <option>10</option>            </select>          </div>        </div>        <div class="col">          <button type="button" class="btn btn-success" onclick=addMerch()>Aggiungi al carrello</button>        </div>      </div>    </div>',
    '<div class="container">      <div class="row">          <h3>Stinco</h3>      </div>      <div class="row">        <div class="col">          <img src="https://content.dambros.it/uploads/2016/03/03103835/0000013354-1024x1024.jpg" border="0" alt="Stinco di maiale" heigt="400" width="273">        </div>        <div class="col">          <p>Lo stinco è un taglio costituito dal garretto del maiale. Solitamente cucinato al forno, alla griglia o bollito. Il piatto richiede una cottura piuttosto lunga, e secondo alcune ricette una marinatura prima della cottura. È molto popolare nelle cucine di diversi Paesi, in particolare in quella tedesca.</p>        </div>      </div>      <div class="row">        <div class="col">          <div class="form-group">            <select class="form-control" id="exampleFormControlSelect1">        <option>0</option>      <option>1</option>              <option>2</option>              <option>3</option>              <option>4</option>              <option>5</option>              <option>6</option>              <option>7</option>              <option>8</option>              <option>9</option>              <option>10</option>            </select>          </div>        </div>        <div class="col">          <button type="button" class="btn btn-success" onclick=addMerch()>Aggiungi al carrello</button>        </div>      </div>    </div>',
    '<p></p>'
];

let merce = ["muso", "orecchio", "testa", "guanciale", "gola", "carre", "capocollo", "spalla", "lombo", "costato", "pancetta", "prosciutto", "stinco"]
let prezzi = [4, 1.20, 7.50, 13.50, 11, 2.50, 7.90, 13, 7.90, 6, 6, 23, 3.70]

const showItems = () => {
  let total=0;
  let oggetti = document.getElementById("items");
  let prezzo = document.getElementById("tot");
  let paga = document.getElementById("pag")
  let g;
  for (g = 0; g < merce.length; g++){
    if(sessionStorage.getItem(merce[g])===null){
      sessionStorage.setItem(merce[g], 0);
    }
    document.getElementById('c'+String(g+1)).innerHTML = merce[g];
    document.getElementById('k'+String(g+1)).innerHTML = sessionStorage.getItem(merce[g]) + "Kg";
    document.getElementById('p'+String(g+1)).innerHTML = sessionStorage.getItem(merce[g])*prezzi[g] + "€";
    total += sessionStorage.getItem(merce[g])*prezzi[g];
  }
  prezzo.insertAdjacentHTML("afterbegin","<div><h2>Totale:</h2><h3>" + total + " € </h3></div>");
} 


const addMerch = () => {
  let f;
  let rip = document.getElementById("riep");
  for (f = 0; f < merce.length; f++){
    //if(sessionStorage.getItem(merce[f]===null)){
      //sessionStorage.setItem(merce[f], 0);
    //}
    //else{
      sessionStorage.setItem(name, document.getElementById("exampleFormControlSelect1").value);
    //}
  }
  $('#acq').toast('show');
  rip.insertAdjacentHTML("afterbegin","<p>Hai un totale di " + document.getElementById("exampleFormControlSelect1").value + " kg. di " + name + "</p>");
};
       
const getLocation = (href) => {
  let l = document.createElement("a");
  l.href = href;
  return l;
};

const riproducisuono = (filename) => {
  var mp3Source = '<source src="' + filename + '.mp3" type="audio/mpeg">';
  var oggSource = '<source src="' + filename + '.ogg" type="audio/ogg">';
  var embedSource = '<embed hidden="true" autostart="true" loop="false" src="' + filename +'.mp3">';
  document.getElementById("sound").innerHTML='<audio autoplay="autoplay">' + mp3Source + oggSource + embedSource + '</audio>';
};

const paga = () => {
  let ps = "";
  let tot = 0;
  let count = -1;
  merce.forEach(e => tot += (parseInt(sessionStorage.getItem(e)) * prezzi[count+=1]));
  merce.forEach(e => ps += "&" + e.charAt(0) + e.charAt(1)+ e.charAt(2) + "=" + sessionStorage.getItem(e));
  location.href = "/pay?email=" + document.getElementById("barra").value + ps + "&tot=" + tot;
  merce.forEach(e => sessionStorage.setItem(e, 0));
}